version: '3.9'

services:
  app:
    container_name: app
    build:
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    env_file:
      - docker/db.env
    ports:
      - '33306:3306'
    volumes:
    - ./_data/mysql:/var/lib/mysql
    - ./docker/db-init:/docker-entrypoint-initdb.d
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
    - ./:/app
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
